version: "3.9"
services:

  postgresdb:
    image: postgres:15-alpine
    container_name: container_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - ./pgdata:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
    container_name: container_app
    environment:
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable
      - HTTP_PORT=${HTTP_PORT}
      - GRPC_PORT=${GRPC_PORT}
    depends_on:
      - postgresdb
    networks:
      - backend
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"

networks:
  backend:
    driver: bridge